/**
 * Migration script generator (#90).
 *
 * Consumes DdlOperation[] from the impact diff engine and produces
 * formatted migration scripts in multiple output formats:
 *   - sql: raw SQL statements
 *   - liquibase-xml: Liquibase XML changesets
 *   - liquibase-yaml: Liquibase YAML changesets
 *   - flyway-sql: Flyway versioned SQL files
 */
import { DdlOperation } from './impactDiff.js';

export type MigrationFormat = 'sql' | 'liquibase-xml' | 'liquibase-yaml' | 'flyway-sql';

export interface MigrationOptions {
  author?: string;
  changesetPrefix?: string;
  includeRollback?: boolean;
  schemaName?: string;
  skipDestructive?: boolean;
}

export interface MigrationResult {
  format: MigrationFormat;
  content: string;
  filename: string;
}

/**
 * Generate a migration script from DDL operations.
 */
export function generateMigration(
  operations: DdlOperation[],
  dialect: string,
  format: MigrationFormat,
  options: MigrationOptions = {},
): MigrationResult {
  const { skipDestructive = false } = options;
  const ops = skipDestructive
    ? operations.filter(o => !o.destructive)
    : operations;

  switch (format) {
    case 'sql':
      return generateRawSql(ops, dialect, options);
    case 'liquibase-xml':
      return generateLiquibaseXml(ops, options);
    case 'liquibase-yaml':
      return generateLiquibaseYaml(ops, options);
    case 'flyway-sql':
      return generateFlywaySql(ops, dialect, options);
    default:
      throw new Error(`Unsupported format: ${format}`);
  }
}

// ────────────────────────────────────────────────────────────────────────
// Raw SQL
// ────────────────────────────────────────────────────────────────────────

function generateRawSql(
  ops: DdlOperation[],
  dialect: string,
  options: MigrationOptions,
): MigrationResult {
  const lines: string[] = [
    `-- Generated by smart-data-dico`,
    `-- Dialect: ${dialect}`,
    `-- Date: ${new Date().toISOString().slice(0, 10)}`,
    '',
  ];

  for (const op of ops) {
    if (op.destructive) {
      lines.push(`-- WARNING: destructive operation (${op.risk})`);
      if (op.riskReason) lines.push(`-- ${op.riskReason}`);
      lines.push(`-- ${op.sql || formatOpDescription(op)}`);
    } else {
      if (op.sql) {
        lines.push(op.sql);
      } else {
        lines.push(`-- TODO: ${formatOpDescription(op)}`);
      }
    }
    lines.push('');
  }

  return {
    format: 'sql',
    content: lines.join('\n'),
    filename: `migration-${new Date().toISOString().slice(0, 10)}.sql`,
  };
}

// ────────────────────────────────────────────────────────────────────────
// Liquibase XML
// ────────────────────────────────────────────────────────────────────────

function generateLiquibaseXml(
  ops: DdlOperation[],
  options: MigrationOptions,
): MigrationResult {
  const author = options.author || 'smart-data-dico';
  const prefix = options.changesetPrefix || 'auto';
  const includeRollback = options.includeRollback ?? false;

  const lines: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<databaseChangeLog',
    '    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"',
    '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
    '    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog',
    '        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">',
    '',
  ];

  ops.forEach((op, i) => {
    const id = `${prefix}-${String(i + 1).padStart(3, '0')}`;
    const comment = op.destructive
      ? `\n    <!-- WARNING: ${op.risk} — ${op.riskReason || 'destructive operation'} -->`
      : '';

    lines.push(`  <changeSet id="${id}" author="${author}">${comment}`);

    switch (op.type) {
      case 'ADD_COLUMN':
        lines.push(`    <addColumn tableName="${op.table}">`);
        lines.push(`      <column name="${op.column}" type="${op.details.dbType || 'VARCHAR(255)'}${op.details.notNull ? '' : ''}" />`);
        lines.push('    </addColumn>');
        if (includeRollback) {
          lines.push('    <rollback>');
          lines.push(`      <dropColumn tableName="${op.table}" columnName="${op.column}" />`);
          lines.push('    </rollback>');
        }
        break;
      case 'DROP_COLUMN':
        lines.push(`    <dropColumn tableName="${op.table}" columnName="${op.column}" />`);
        if (includeRollback) {
          lines.push('    <rollback>');
          lines.push(`      <addColumn tableName="${op.table}"><column name="${op.column}" type="VARCHAR(255)" /></addColumn>`);
          lines.push('    </rollback>');
        }
        break;
      case 'ALTER_COLUMN':
        lines.push(`    <modifyDataType tableName="${op.table}" columnName="${op.column}" newDataType="${op.details.to || 'VARCHAR(255)'}" />`);
        break;
      case 'CREATE_TABLE':
        lines.push(`    <createTable tableName="${op.table}">`);
        // Columns embedded in SQL — extract from details
        lines.push(`      <!-- Columns: ${op.details.columns || 'see SQL'} -->`);
        lines.push('    </createTable>');
        break;
      case 'DROP_TABLE':
        lines.push(`    <dropTable tableName="${op.table}" />`);
        break;
      case 'ADD_CONSTRAINT':
      case 'ADD_INDEX':
      case 'ADD_FOREIGN_KEY':
        lines.push(`    <!-- ${op.type}: ${op.details.key || ''} -->`);
        if (op.sql) lines.push(`    <sql>${escapeXml(op.sql)}</sql>`);
        break;
      case 'DROP_CONSTRAINT':
      case 'DROP_INDEX':
      case 'DROP_FOREIGN_KEY':
        lines.push(`    <!-- ${op.type}: ${op.details.key || ''} -->`);
        if (op.sql) lines.push(`    <sql>${escapeXml(op.sql)}</sql>`);
        break;
    }

    lines.push('  </changeSet>');
    lines.push('');
  });

  lines.push('</databaseChangeLog>');

  return {
    format: 'liquibase-xml',
    content: lines.join('\n'),
    filename: `changelog-${new Date().toISOString().slice(0, 10)}.xml`,
  };
}

// ────────────────────────────────────────────────────────────────────────
// Liquibase YAML
// ────────────────────────────────────────────────────────────────────────

function generateLiquibaseYaml(
  ops: DdlOperation[],
  options: MigrationOptions,
): MigrationResult {
  const author = options.author || 'smart-data-dico';
  const prefix = options.changesetPrefix || 'auto';
  const includeRollback = options.includeRollback ?? false;

  const lines: string[] = ['databaseChangeLog:'];

  ops.forEach((op, i) => {
    const id = `${prefix}-${String(i + 1).padStart(3, '0')}`;
    lines.push(`  - changeSet:`);
    lines.push(`      id: "${id}"`);
    lines.push(`      author: "${author}"`);

    if (op.destructive) {
      lines.push(`      comment: "WARNING: ${op.risk} — ${op.riskReason || 'destructive'}"`);
    }

    lines.push(`      changes:`);

    switch (op.type) {
      case 'ADD_COLUMN':
        lines.push(`        - addColumn:`);
        lines.push(`            tableName: "${op.table}"`);
        lines.push(`            columns:`);
        lines.push(`              - column:`);
        lines.push(`                  name: "${op.column}"`);
        lines.push(`                  type: "${op.details.dbType || 'VARCHAR(255)'}"`);
        if (includeRollback) {
          lines.push(`      rollback:`);
          lines.push(`        - dropColumn:`);
          lines.push(`            tableName: "${op.table}"`);
          lines.push(`            columnName: "${op.column}"`);
        }
        break;
      case 'DROP_COLUMN':
        lines.push(`        - dropColumn:`);
        lines.push(`            tableName: "${op.table}"`);
        lines.push(`            columnName: "${op.column}"`);
        break;
      case 'ALTER_COLUMN':
        lines.push(`        - modifyDataType:`);
        lines.push(`            tableName: "${op.table}"`);
        lines.push(`            columnName: "${op.column}"`);
        lines.push(`            newDataType: "${op.details.to || 'VARCHAR(255)'}"`);
        break;
      case 'CREATE_TABLE':
        lines.push(`        - createTable:`);
        lines.push(`            tableName: "${op.table}"`);
        break;
      default:
        if (op.sql) {
          lines.push(`        - sql:`);
          lines.push(`            sql: "${op.sql.replace(/"/g, '\\"')}"`);
        } else {
          lines.push(`        # ${op.type}: ${op.details.key || ''}`);
        }
    }
  });

  return {
    format: 'liquibase-yaml',
    content: lines.join('\n'),
    filename: `changelog-${new Date().toISOString().slice(0, 10)}.yaml`,
  };
}

// ────────────────────────────────────────────────────────────────────────
// Flyway SQL
// ────────────────────────────────────────────────────────────────────────

function generateFlywaySql(
  ops: DdlOperation[],
  dialect: string,
  options: MigrationOptions,
): MigrationResult {
  const prefix = options.changesetPrefix || 'V1';
  const lines: string[] = [];

  ops.forEach((op, i) => {
    const version = `${prefix}.${String(i + 1).padStart(3, '0')}`;
    const desc = formatOpDescription(op).replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '');
    lines.push(`-- ${version}__${desc}`);
    if (op.destructive) {
      lines.push(`-- WARNING: ${op.risk} — ${op.riskReason || 'destructive operation'}`);
      lines.push(`-- ${op.sql || formatOpDescription(op)}`);
    } else if (op.sql) {
      lines.push(op.sql);
    } else {
      lines.push(`-- TODO: ${formatOpDescription(op)}`);
    }
    lines.push('');
  });

  return {
    format: 'flyway-sql',
    content: lines.join('\n'),
    filename: `${prefix}__migration.sql`,
  };
}

// ────────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────────

function formatOpDescription(op: DdlOperation): string {
  if (op.column) return `${op.type} ${op.table}.${op.column}`;
  return `${op.type} ${op.table}`;
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
