#!/usr/bin/env node

/**
 * Bundle the backend into a single ESM file using esbuild.
 *
 * This eliminates the need for tsx at runtime and removes all module-resolution
 * issues when the package is installed via npm/npx (dependencies live in a
 * parent node_modules that tsx can't find).
 *
 * swagger-ui-express is excluded because it serves static assets from disk
 * that can't be inlined. Swagger is made optional at runtime (dev-only).
 */

import { build } from 'esbuild';
import { rmSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// Clean previous build
rmSync(join(root, 'backend', 'dist'), { recursive: true, force: true });

await build({
  entryPoints: [join(root, 'backend', 'src', 'server.ts')],
  outfile: join(root, 'backend', 'dist', 'server.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node18',
  sourcemap: false,
  minify: false,          // keep readable for debugging
  keepNames: true,        // preserve function/class names

  // All dependencies are bundled — no external packages needed at runtime.
  // swagger-ui-express is bundled too; its static assets won't exist in
  // production, but setupSwagger is inside a try-catch so it's harmless.

  // Shim import.meta.url so path resolution still works in the bundle
  define: {},

  banner: {
    js: [
      '// Bundled backend — generated by scripts/build-backend.mjs',
      '// Do not edit directly; modify backend/src/ and rebuild.',
      '',
      '// CJS interop: Express and deps use require() for Node builtins',
      'import { createRequire as __bundled_createRequire } from "module";',
      'const require = __bundled_createRequire(import.meta.url);',
    ].join('\n'),
  },

  logLevel: 'info',
});

console.log('\n✓ Backend bundled to backend/dist/server.mjs');
