#!/usr/bin/env node

/**
 * Bundle the backend into a single ESM file using esbuild.
 *
 * This eliminates the need for tsx at runtime and removes all module-resolution
 * issues when the package is installed via npm/npx (dependencies live in a
 * parent node_modules that tsx can't find).
 *
 * swagger-ui-express is excluded because it serves static assets from disk
 * that can't be inlined. Swagger is made optional at runtime (dev-only).
 */

import { build } from 'esbuild';
import { rmSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// Clean previous build
rmSync(join(root, 'backend', 'dist'), { recursive: true, force: true });

// Shared esbuild options for every backend entry point we bundle.
const common = {
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node18',
  sourcemap: false,
  minify: false,          // keep readable for debugging
  keepNames: true,        // preserve function/class names

  // All dependencies are bundled — no external packages needed at runtime
  // EXCEPT the database drivers below. Drivers are loaded via dynamic
  // `import()` inside try/catch in services/{oracle,mysql,postgres,mssql}Introspect.ts
  // and are declared as optional peer deps so installs that don't need
  // physical-DB introspection skip ~8MB of driver source.
  // swagger-ui-express is bundled too; its static assets won't exist in
  // production, but setupSwagger is inside a try-catch so it's harmless.
  external: [
    'oracledb',
    'mysql2',
    'mysql2/promise',
    'pg',
    'mssql',
    // fsevents is a macOS-only native module pulled in transitively by
    // chokidar (RawFsWatcher slice 6e.2). esbuild can't bundle a `.node`
    // binary; chokidar's own loader is `try { require('fsevents') }
    // catch {}`, so leaving it external is safe — npm installs it on
    // darwin and skips it elsewhere.
    'fsevents',
  ],

  define: {},

  banner: {
    js: [
      '// Bundled backend — generated by scripts/build-backend.mjs',
      '// Do not edit directly; modify backend/src/ and rebuild.',
      '',
      '// CJS interop: Express and deps use require() for Node builtins',
      'import { createRequire as __bundled_createRequire } from "module";',
      'const require = __bundled_createRequire(import.meta.url);',
    ].join('\n'),
  },

  logLevel: 'info',
};

// 1) The HTTP server — the package's main runtime entry.
await build({
  ...common,
  entryPoints: [join(root, 'backend', 'src', 'server.ts')],
  outfile: join(root, 'backend', 'dist', 'server.mjs'),
});
console.log('\n✓ Backend bundled to backend/dist/server.mjs');

// 2) The standalone project validator — spawned by `bin/cli.js --validate`
//    so `npx @hamak/smart-data-dico --validate <folder>` works with no tsx.
await build({
  ...common,
  entryPoints: [join(root, 'backend', 'src', 'scripts', 'validateDico.ts')],
  outfile: join(root, 'backend', 'dist', 'validate.mjs'),
});
console.log('✓ Validator bundled to backend/dist/validate.mjs');
